Repository scombz-utilities/scombz-utilities-react, pull requests merged in 2024-05, with the labels that each got.

#28 Improve/adfs login form
  src/contents/components/SaveDialog.tsx
Labels: enhancement

#51 add pr-agent
  .github/workflows/pr-agent.yml
Labels: enhancement, Review effort [1-5]: 2

#54 Feature/Layout subjects
  assets/close_button.gif
  assets/open_button.gif
  css/hide_material_button.css
  package-lock.json
  package.json
  src/backgrounds/migration.ts
  src/contents/addOriginalTaskInCourse.tsx
  src/contents/course.ts
  src/contents/util/courseLogic.ts
  src/contents/util/functions.ts
  src/contents/util/layoutSubject.ts
  src/options/components/AdvancedOptions.tsx
  src/options/components/BasicOptions.tsx
  src/options/components/SortableTable.tsx
  src/settings.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#52 Improve/options tab
  locales/ja/messages.json
  src/options/components/AdvancedOptions.tsx
  src/options/components/BasicOptions.tsx
  src/options/components/ComplexOptions.tsx
  src/options/components/LayoutOptions.tsx
  src/options/components/RecommendedOptions.tsx
  src/options/components/SimpleOptions.tsx
  src/options/components/WidgetOptions.tsx
  src/options/index.css
  src/options/index.tsx
Labels: enhancement, Review effort [1-5]: 4

#58 v4.0.0の時は専用LPを開くように変更
  src/background.ts
  src/backgrounds/onInstalled.ts
Labels: enhancement, Review effort [1-5]: 2

#61 Feature/fix migration
  README.md
  src/backgrounds/migration.ts
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#63 レポート入力ボタンバグ修正 & css適用
  css/min_input_buttons.css
  src/contents/changeReportButton.ts
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#65 feat: 課題一覧を再取得するボタンを追加
  locales/en/messages.json
  locales/ja/messages.json
  src/contents/components/TaskList.tsx
Labels: documentation, enhancement, Review effort [1-5]: 2

#67 Docs/description and i18n
  locales/en/messages.json
  locales/ja/messages.json
  src/contents/components/SaveDialog.tsx
  src/contents/components/UserMemo.tsx
  src/options/components/AdvancedOptions.tsx
  src/options/components/BasicOptions.tsx
  src/options/components/Information.tsx
  src/options/components/LayoutOptions.tsx
  src/options/components/blocks/CustomContainerParent.tsx
  src/options/components/blocks/CustomRemovableList.tsx
  src/options/components/blocks/CustomSelect.tsx
  src/options/components/blocks/CustomSwitch.tsx
  src/options/components/blocks/CustomTextField.tsx
  src/options/components/blocks/Editor.tsx
  src/options/components/blocks/OptionGroup.tsx
  src/options/components/blocks/SortableTable.tsx
  src/options/components/pages/AdvancedOptions.tsx
  src/options/components/pages/BasicOptions.tsx
  src/options/components/pages/CustomCSS.tsx
  src/options/components/pages/DataOperation.tsx
  src/options/components/pages/Information.tsx
  src/options/components/pages/LayoutOptions.tsx
  src/options/components/pages/WidgetOptions.tsx
  src/options/index.css
  src/options/index.tsx
Labels: documentation, enhancement, Review effort [1-5]: 4
