Repository scombz-utilities/scombz-utilities-react, pull requests merged in 2024-06, with the labels that each got.

#70 ctrl + clickでホイールクリック判定にする
  src/contents/mouseDownEvent.ts
Labels: enhancement, Review effort [1-5]: 2

#72 feat: courseページにクイックメニューを追加
  css/quickmenu.css
  src/contents/course.ts
  src/contents/util/layoutSubject.ts
Labels: enhancement, Review effort [1-5]: 2

#74 Fix/layouts
  css/quickmenu.css
  css/side_menu.css
  src/options/components/blocks/CustomTextField.tsx
  src/options/components/pages/AdvancedOptions.tsx
  src/options/components/pages/BasicOptions.tsx
  src/options/components/pages/WidgetOptions.tsx
  src/options/index.tsx
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#75 fix: sidemenuでページ内リンクやダイアログ表示をクリックしたときの表示を修正
  css/side_menu.css
  src/contents/sideMenu.ts
Labels: enhancement, Review effort [1-5]: 2

#76 feat: emailをコピーできる機能を追加
  css/emails.css
  css/quickmenu.css
  src/contents/course.ts
  src/contents/util/courseLogic.ts
Labels: enhancement, Review effort [1-5]: 3

#81 Feature/stable release
  src/contents/components/Calendar.tsx
  src/contents/components/TaskList.tsx
  src/contents/components/WidgetWrapper.tsx
  src/contents/menuWidget.tsx
  src/contents/tasks.ts
  src/contents/types/calendar.d.ts
  src/contents/types/widget.d.ts
  src/contents/util/getTaskList.ts
  src/options/components/pages/WidgetOptions.tsx
  src/popup/components/TasksBottom.tsx
  src/settings.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#84 fix: popupから課題一覧を取得するとtask.linkのoriginがおかしくなる
  src/contents/util/getTaskList.ts
Labels: Review effort [1-5]: 2, Bug fix

#85 dark modeの実装
  package.json
  src/backgrounds/onInstalled.ts
  src/contents/addOriginalTaskInCourse.tsx
  src/contents/components/AutoComplete.tsx
  src/contents/components/Bus.tsx
  src/contents/components/Calendar.tsx
  src/contents/components/Links.tsx
  src/contents/components/TaskList.tsx
  src/contents/components/TimeTable.tsx
  src/contents/components/UserMemo.tsx
  src/contents/layout.ts
  src/contents/menuWidget.tsx
  src/contents/util/darkModeCSS.ts
  src/options/components/pages/LayoutOptions.tsx
  src/settings.ts
  src/theme.ts
Labels: enhancement, Review effort [1-5]: 4, Other

#87 fix: popupから課題取得時、Firefoxの場合は代わりに課題一覧を開くように
  locales/en/messages.json
  locales/ja/messages.json
  src/contents/tasks.ts
  src/popup/components/TasksBottom.tsx
Labels: Review effort [1-5]: 2, Bug fix

#88 FireFoxのv4.0.0仮対応
  publish/chrome_webstore_pic/image4.png
  src/backgrounds/onInstalled.ts
  src/contents/components/firefoxWidgetStyle.module.css
  src/contents/components/menuWidgetChrome.tsx
  src/contents/components/menuWidgetFirefox.tsx
  src/contents/menuWidget.tsx
  src/contents/onDocumentStart.ts
  src/options/container/chrome.css
  src/options/container/chrome.tsx
  src/options/container/firefox.css
  src/options/container/firefox.tsx
  src/options/index.tsx
Labels: enhancement, Review effort [1-5]: 4, Other

#90 fix darkmode color
  package-lock.json
  src/contents/components/Bus.tsx
  src/contents/components/Calendar.tsx
  src/contents/components/Links.tsx
  src/contents/components/TaskList.tsx
  src/contents/components/TimeTable.tsx
  src/contents/components/UserMemo.tsx
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#91 [fix] README.mdの修正
  README.md
Labels: documentation, Review effort [1-5]: 1

#92 Feature/miuye css
  src/contents/util/darkModeCSS.ts
  src/options/components/pages/LayoutOptions.tsx
Labels: enhancement, Review effort [1-5]: 2

#98 LMSに「編集可能な授業」がある場合に取得エラーが起きる問題を修正
  src/contents/util/getLMS.ts
  src/contents/util/layoutSubject.ts
Labels: Review effort [1-5]: 2, Bug fix

#99 fix firefox widget css
  src/contents/components/firefoxWidgetStyle.module.css
  src/contents/menuWidget.tsx
  src/contents/util/functions.ts
  src/popup/index.tsx
Labels: enhancement, Review effort [1-5]: 2

#104 自動アップロードスクリプトを作成
  .gitignore
  package-lock.json
  package.json
  src/contents/tasks.ts
Labels: enhancement, dependencies
